# Generated by Django 4.1.3 on 2023-01-05 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmployeeData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(max_length=20)),
                ("email", models.CharField(max_length=128)),
                (
                    "position",
                    models.IntegerField(
                        choices=[
                            (0, "Backenddeveloper"),
                            (1, "Frontenddeveloper"),
                            (2, "Hr"),
                            (3, "Techsupport"),
                            (4, "Qa"),
                            (5, "Marketer"),
                            (6, "Accountant"),
                            (7, "Projectmanager"),
                        ]
                    ),
                ),
                ("bank_account", models.CharField(max_length=128)),
                ("salary", models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.CharField(max_length=128)),
                (
                    "employee_data",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ui.employeedata",
                    ),
                ),
            ],
        ),
    ]
