# Generated by Django 4.1.3 on 2023-01-05 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0002_alter_person_employee_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="subscription",
            field=models.BooleanField(null=True),
        ),
    ]
